# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go generate ./...
builds:
  -
    main: ./router.go
    binary: router
    env:
    - CGO_ENABLED=0
      # - GO11MODULE=on
    ldflags:
      - -extldflags -s -X main.version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
